name: website

on:
  push:
    branches:
        - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: 'npm install -g yarn'
      - run: 'yarn install'
      - run: 'yarn build'
      -
        name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: static
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}